### DISCUSSION TITLE
Problem with konfiguration

### DISCUSSION THREAD

**Discussion by benzoesaeure** [mak-gitdev/HA_enoceanmqtt#107] [Q&A]
hi, I have now installed the addon. I'm having trouble with the configuration. I created the folder config/enoceanmqtt.devices with File edition. I copied the content completely from GitHub. I added the USB 300 as an interface. I left mqtt open because I use mosquito. I always get the info waiting for device base ide.

**Comment by mak-gitdev** [comment]
Hi @benzoesaeure, 

Please share your device file as well as your addon configuration.

**Comment by benzoesaeure** [comment]
Good morning,
in /config/enoceanmqtt.devices
```
[rocker_1]
address         = 0xBABECAFE
rorg            = 0xF6
func            = 0x02
type            = 0x02

[virtual_rocker]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFDA5580
virtual 		= 1

[smoke_detector]
address         = 0xABADC0DE
rorg            = 0xA5
func            = 0x02
type            = 0x05

[shutter]
address         = 0x12345678
rorg            = 0xD2
func            = 0x05
type            = 0x00

[pilotwire]
address         = 0xDEADBEEF
rorg            = 0xD2
func            = 0x01
type            = 0x0C

[non_interesting]
address         = 0xBAAAAAAD
# This sensor will be ignored
ignore          = 1
```


konfig : 

```yaml
device_file: /config/enoceanmqtt.devices
mapping_file: ""
eep_file: ""
log_file: /config/enoceanmqtt.log
enocean_port: /dev/serial/by-id/usb-EnOcean_GmbH_USB_300_DE_EO76FR5G-if00-port0
debug: true
log_packets: true
use_dev_name_in_entity: true
mqtt_broker: {}
mqtt_discovery_prefix: homeassistant
mqtt_prefix: enoceanmqtt
mqtt_client_id: enocean_gateway
mqtt_keepalive: 60
```
