### DISCUSSION TITLE
Covers: unsupported tilt feature

### DISCUSSION THREAD

**Discussion by OlwinFroon** [mak-gitdev/HA_enoceanmqtt#119] [Request]
E2M cover entities seem to enable tilt angle support by default because it is a feature in the D2-05-00/02 EEP, regardless if the device really supports it or not.

As a result, these devices show up with a useless and nonfunctional tilt angle control in HA.

Right now, I disable these useless controls by adding this to my configuration.yaml:

```
homeassistant:
  customize:
    cover.my_cover_1:
      supported_features: 15
    cover.my_cover_2:
      supported_features: 15
    cover.my_cover_3:
      supported_features: 15
```

Features supported by the cover component are 
OPEN = 1
CLOSE = 2
SET_POSITION = 4
STOP  = 8
OPEN_TILT = 16
CLOSE_TILT = 32
STOP_TILT  = 64
SET_TILT_POSITION = 128

See [HERE](https://github.com/home-assistant/core/blob/dev/homeassistant/components/cover/__init__.py)

A cover device that supports only part of these should set the device's `supported_features` attribute accordingly by summing up the numbers attached to this list. 15 means 1+2+4+8 = everything not involving tilt.

I'm wondering if we could have this in the E2M configuration.
Perhaps an optional parameter to the device file?
