### DISCUSSION TITLE
Working with Eltako FAM14

### DISCUSSION THREAD

**Discussion by magic2910** [mak-gitdev/HA_enoceanmqtt#16] [Q&A]
Hi all,
I am looking for an home Assistant addon to manage my Eltako FUD14 Dimmers and FSR14-2x connected via FAM14.
Is this possible with this addon?

**Comment by mak-gitdev** [comment]
Hi,

This is not yet available but definitely in the todo list.

See #1 and this [discussion](https://community.home-assistant.io/t/enocean-with-ha-enoceanmqtt/491606) on HA forum

**Comment by Sentinel-sys** [comment]
Hi all,

is there some new information about FAM14 integration. I followed the links and read all the posts but at some point I got confussed and gave up.
I understood that there is a hacky way and a proper way to get this working. I would try the proper way but I get lost in "tech speak" :-)

Also it is quite tricky to follow along with all this forums, discussions, posts and so on.

I would like to contribute a write an wiki article of some sort. But for this I first need to understood how it works and then get it working by myself.

Anyone how is willing to help me. I have the hardware here:

FAM14
FSB14
F4SR14-LED
USB300

Installed Home Assistant and HA-enoceanmqtt-addon

Thank you
Joe

**Comment by tbarbette** [comment]
I've got the exact same setup.

First launch the enoceanmqtt with the default enoceanmqtt.conf correctly configured but don't bother adding buttons or else. The idea is to recover the baseid of your USB300 in the MQTT integration.
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/8c54334c-b7e1-4baf-b381-6726f6172c1e)
You'll have normally one device, look for that : 
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/dec602c5-4f70-44e5-a44c-3ebfa6f7fef2)

And get the base id there :
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/ad4551f6-cd48-439e-8eb5-43e409450710)


Then, with the base ID you can invent some sender IDs to create virtual switch buttons, exactly like the physical ones you probably have.
Add the following for each light (yes, it will be long). My base id is 0xFFEDA9XX. I used the number of my relays as last digits.

```
[relay/PorchLight]
address = 0xFFFFFFFF
sender = 0xFFEDA921
rorg    = 0xF6
func    = 0x02
type     = 0x01
virtual = 1
```

Then, the button will appear in Home Assistant.
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/6b7ec83c-88b3-4e0f-90e0-79a1b4399836)
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/9ef39654-e3dd-4d30-88d4-ee47f10622ab)

A0, A1, B0, B1 are basically like pressing the 4 buttons of the physical switches.
You can start the learning process on your F4SR14-LED like the physical switches, one by one. Yes it's long and painful.

Basically now it should work, but the buttons are not very convenient... So what you want is to create virtual "template" switch. But first, for those button to reflect the state of your light, you want also to integrate the feedback from the FAM14. After actionning each interruptor (virtual or physical), you'll get a message in "response" to the  switch being pressed in the enoceanmqtt log. 

Why? Even if you manage to record the state when you interact with relays from HA, the physical buttons are still there and you want their feedback too.

Create "state" entities in enoceanmqtt.conf with the address, one by one:

```
[relay_state/Porch]
rorg    = 0xf6
func = 0x02
type = 0x01
address = 0xFFE80D01
```
The funny part is that it's the same device type. The reason is the FAM14 basically echo the datagram with the current state of the relay. So it appears as a switch... But it actually reflects the state of the relay :) 

Okay, you get the "actioner", and the "state", let's build a nice button out of that :

```
switch:
  - platform: template                                                                                                                                                                                                                                        
     switches:
      porch_light:                                                                                                                                                                                                                                                        
        friendly_name: Porch power
        value_template: "{{ is_state('binary_sensor.e2m_relay_state_porch_bo_pressed', 'on') }}"
        turn_on:
          - service: select.select_option
            data:
              option: AO
            target:
              entity_id: select.e2m_relay_porchlight_action
        turn_off:
          - service: select.select_option
            data:
              option: AI
            target:
              entity_id: select.e2m_relay_porchlight_action
```

And tadaaam :
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/248961/cf004ce2-3d23-45d6-aee4-9df3c29d48da)


A bit painfull to create 24 relays, but once done it works like a charm :)
