### DISCUSSION TITLE
F6-02-01 Long Press Issue

### DISCUSSION THREAD

**Discussion by ich777** [mak-gitdev/HA_enoceanmqtt#168] [Q&A]
I have a question about the F6-02-01 switch modules.
Currently if I create a automation in HomeAssistant with short and long press, however when I press the button, to initiate a long press, the short press action triggers and when I release the button the long press action triggers.

Is it somehow possible to reliably detect the long press or at least have something like with the D2‐03‐0A with long and short press, maybe a virtual button could be added like long press release.

Would something like that be possible at all or do I overthink that all since I haven't been able to solve that yet.

Currently I'm using the Fork from @madejackson but I post here since there is no issue tracker or similar enabled over there.

**Comment by madejackson** [comment]
Hey,
The worlds small. I've been using your gameserver templates several times ✌🏻

Anyways. You need to do a special automation for it to work. Here's my automation to have a long press dim function:

(I'd help you more but I'm not at a desktop right now)

```
alias: "Stehlampe Wozi: Toggle / Dim"
description: ""
mode: single
triggers:
  - type: turned_on
    device_id: 6276d884793923a35e64f145e80685c3
    entity_id: a23227020d819579c972f53c4ae1b583
    domain: binary_sensor
    id: AI long
    for:
      hours: 0
      minutes: 0
      seconds: 1
    trigger: device
  - type: turned_off
    device_id: 6276d884793923a35e64f145e80685c3
    entity_id: a23227020d819579c972f53c4ae1b583
    domain: binary_sensor
    id: AI short
    trigger: device
  - type: turned_on
    device_id: 6276d884793923a35e64f145e80685c3
    entity_id: 6b5596cb7c323fa076ba9edfc4b75f29
    domain: binary_sensor
    id: AO long
    for:
      hours: 0
      minutes: 0
      seconds: 1
    trigger: device
  - type: turned_off
    device_id: 6276d884793923a35e64f145e80685c3
    entity_id: 6b5596cb7c323fa076ba9edfc4b75f29
    domain: binary_sensor
    id: AO short
    trigger: device
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - AI long
        sequence:
          - repeat:
              sequence:
                - device_id: 8007931eff6f22bcd5e911924012be9a
                  domain: light
                  entity_id: bdc33574d487c6c150be9b1c644f6bf3
                  type: brightness_increase
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 250
              while:
                - type: is_on
                  condition: device
                  device_id: 6276d884793923a35e64f145e80685c3
                  entity_id: 90ec60de230745639a7bfe50367af823
                  domain: binary_sensor
      - conditions:
          - condition: trigger
            id:
              - AO long
        sequence:
          - repeat:
              sequence:
                - device_id: 8007931eff6f22bcd5e911924012be9a
                  domain: light
                  entity_id: bdc33574d487c6c150be9b1c644f6bf3
                  type: brightness_decrease
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 250
              while:
                - type: is_on
                  condition: device
                  device_id: 6276d884793923a35e64f145e80685c3
                  entity_id: 90ec60de230745639a7bfe50367af823
                  domain: binary_sensor
      - conditions:
          - condition: trigger
            id:
              - AI short
        sequence:
          - type: turn_on
            device_id: 8007931eff6f22bcd5e911924012be9a
            entity_id: bdc33574d487c6c150be9b1c644f6bf3
            domain: light
      - conditions:
          - condition: trigger
            id:
              - AO short
        sequence:
          - type: turn_off
            device_id: 8007931eff6f22bcd5e911924012be9a
            entity_id: bdc33574d487c6c150be9b1c644f6bf3
            domain: light

```
