### DISCUSSION TITLE
some thoughts about the FTKE devices bypassing power cuts

### DISCUSSION THREAD

**Discussion by commentsonly** [mak-gitdev/HA_enoceanmqtt#19] [Show and tell]
had some time yesterday playing with me recently bought FTKE gadgets.

And did run into the very first issue which goes like this:

Anyone with a working flow to get the correct states from FTKE sensors beyond a power failure? Found nothing on the HA community forum, but granted if ever 0.x% might use EnOcean devices since integration wasn't up to what it should have been. Since so perhaps someone got an answer since chances given EnOcean experts will be found here.

Ok, If this happens (power cut) the self-harvesting FTKE doesn't care much about it and simply sends it's message if someone opens a window within that period.

But the receiver (HA) won't listen since being not running on a self-harvesting machine. sigh!!! Means the information inside the message sent wasn't received but lost.

My first solution was to implement a template trigger in the form

```
template:
  - trigger:
      - platform: state
        entity_id: binary_Sensor.e2m_ftke_wohnzimmer_state_2p
        from: 'on'
        to: 'off'
    sensor:
      - name: ftke_wohnzimmer_opened
        state: "{{ as_timestamp(now()) | float(0) | timestamp_custom }}"
```
which does catch the timestamp the FTKE switched it's state (in fact I simply created to of them for testing to have closed and opened timestamps. Then I can compare this against the HA last_boot timestamp. And depending upon which one happened earlier I can either block all roller shutters since a state change which did happen before a power cut of the HA machine is free from sense, whereas if all my FTKE had state changes after HA was booted the chance is given that the FTKW state reflects the real state.
If the state is uncertain my workflow is to run around the house opening/closing all windows untl the last_boot becomes the oldest timestamp which then leads to re-enabling the roller shutters. (better said allowing the roller shutters to act again).

2 benefits: my doctor would congratulate for the "running around the house idea which adds something positive to my health condition" and ... it ensure my window frames (opening to the outside) aren't decorated with scratches by the shutters any more.

addon: because I do dislike in clustering solutions into pieces noone brings together in the end I played with the mapping.yaml
and simply added the following lines to the F6-10-00 section

```
            - component: sensor
              name: "state_4p"
              config:
                state_topic: ""
                value_template: >-
                  {% if value_json.WIN == 3 %}{{as_timestamp(now())|float(0)|timestamp_custom}}{% else %}{{as_timestamp(now())|float(0)|timestamp_custom}}{% endif %}
```
what happens is you get the state switch time delivered together with the already delivered 2p  and 3p state, means no need to configure the template trigger. and sure I should have used a differnt name bust state_p4 .. (timestamp or somthing like that) and perhaps it could have been something from the type diagnostic. I'm happy I even got it working .....

![snapped](https://user-images.githubusercontent.com/35866491/204049564-32f6a3cc-5851-40ec-a4df-7698b50952fc.png)

Coming back to where I started ... the power cut problem.
The only other idea whicht might allow to get rid of the "running around the house" might be an emergency power supply for my HA machine so that it won't accidently miss messages which were accurately sent by the FTKE.
But if someone has a different solution this one is far from being ideal.
