### DISCUSSION TITLE
Is it possible to  send radio telegrams?

### DISCUSSION THREAD

**Discussion by tzippy84** [mak-gitdev/HA_enoceanmqtt#22] [Q&A]
I was wondering if its also possible to somehow send telegrams through an automation? How would I do that?
Thank you!

**Comment by mak-gitdev** [comment]
Hi,

I need more details to give you an accurate answer.
Which radio telegram do you want to send, or which EnOcean device do you want to control ?

**Reply by tzippy84** [reply]
sorry, here's some more details: 
I have a TCM300 transceiver module connected to an arduino that controls a couple of LEDs. It runs a simple program that listens to all enocean radio packets. It only acts on a certain ID (simple byte compare) from one PTM210 rocker switch.
So I am pretty free in what I can do on the receiving side of the Arduino.
The most simple thing (for me ) would be to send the same F6-02-01 telegrams that the Arduino now listens to.

**Reply by mak-gitdev** [reply]
Ok I see.

You can do it, even if for the moment, it is not fully supported and not intended to work like that.
I mean, I made this work having in mind that F6 telegrams will always come to HA, I never had the use case to generate such telegrams in my applications.
But as this is of interest, especially for Eltako users, it will be fully supported in a future version I will start working on soon.

Please see [this discussion](https://github.com/mak-gitdev/HA_enoceanmqtt/discussions/1#discussioncomment-4129073) for how to do it.
Note that if you use the dev version of the addon (I recommend to use this version), the base id is now easily available. See #17 for more details.

**Reply by mak-gitdev** [reply]
Do not hesitate if you have questions.

Also please report here if you have any success.
I am waiting for a confirmation that the described procedure works well before starting implementing it.

**Comment by tzippy84** [comment]
I tried following the steps from the topic you linked. But when you write "So, for the moment, please define 2 MQTT sensors like this:“ I’m not sure how to manually configure MQTT entities. Where would I put the yaml configuration? If I paste it into my configuration.yaml I get an error saying „Property button is not allowed“.
I am new to MQTT broker. 
Thanks!

**Reply by mak-gitdev** [reply]
Which version of HA are you using ?

**Comment by tzippy84** [comment]
2022.11.4

mak-gitdev ***@***.***> schrieb am Mi. 30. Nov. 2022 um 05:50:

**Reply by mak-gitdev** [reply]
I think it should be ok.

May I see your configuration.yaml ? Please mask all sensitive data before publishing it.

**Comment by tzippy84** [comment]
Sure. Here it is. Nothing too fancy going on I think:

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

powercalc:

image_processing:
  - platform: doods
    url: http://192.168.0.136:8080
    detector: default
    scan_interval: 1
    source:
      - entity_id: camera.mobotix_i26
    file_out: /config/www/doods_{{ camera_entity.split('.')[1] }}_latest.jpg
    confidence: 60
    labels:
      - name: car
        confidence: 70
      - name: person
        confidence: 70
      - truck

camera:
  - platform: generic
    name: doods_cam
    still_image_url: http://192.168.0.136:8123/local/doods.jpg

sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone2/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: processor_use
      - type: disk_use_percent
        arg: "/"
      - type: disk_free
        arg: "/"
      - type: memory_use_percent
      - type: network_in
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: processor_temperature
      - type: last_boot

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  allowlist_external_dirs:
    - /config/tmp
    - /config/www


utility_meter:
  util_water_usage_hourly:
    source: sensor.water_total
    cycle: hourly
  util_water_usage_daily:
    source: sensor.water_total
    cycle: daily
  util_water_usage_monthly:
    source: sensor.water_total
    cycle: monthly
  util_water_usage_yearly:
    source: sensor.water_total
    cycle: yearly
```
