### DISCUSSION TITLE
A5-10-06 (Eltako)

### DISCUSSION THREAD

**Discussion by HotteX** [mak-gitdev/HA_enoceanmqtt#33] [Request] [answered]
Cheerio,

a request for a "Thermostate" by Eltako. I got part of the mapping working fine but this device has 2 specialities, that are too complicated for my current state of knowledge:

1st: Temperature. This works.

2nd: A setpoint. I get the raw value in my entity, but it would be more helpful to have a temperature value. 
According to specs that means: Value * 0,157°C (just like TMP, only not reversed. TMP is 255..0)
Eltako writes:
Data_byte2 = 0..40°C (0..255)
Set Point range: 12..28°C

3rd: A slide switch with 3 states (Day, Off, Night with values 1 and 0 (off being really off it seems).

```
2023-01-22 22:41:15,457 DEBUG: FF:A0:C8:00->FF:FF:FF:FF (-74 dBm): 0x01 ['0xa5', '0x0', '0x4c', '0x94', '0xf', '0xff', '0xa0', '0xc8', '0x0', '0x0'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x4a', '0x0'] OrderedDict()
2023-01-22 22:41:15,468 DEBUG: enoceanmqtt/Temp/UG_Wohnzimmer: SP (Set Point (linear))=76.0 %
2023-01-22 22:41:15,470 DEBUG: FF:A0:C8:01->FF:FF:FF:FF (-74 dBm): 0x01 ['0xa5', '0x0', '0x0', '0x0', '0x8', '0xff', '0xa0', '0xc8', '0x1', '0x0'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x4a', '0x0'] OrderedDict()
2023-01-22 22:41:15,472 DEBUG: enoceanmqtt/Temp/UG_Wohnzimmer: TMP (Temperature (linear))=16.784313725490197 °C
2023-01-22 22:41:15,475 DEBUG: enoceanmqtt/Temp/UG_Wohnzimmer: SLSW (Slide switch)=Position O / Day / On 
2023-01-22 22:41:15,476 DEBUG: enoceanmqtt/Temp/UG_Wohnzimmer: Sent MQTT: {"RSSI": -74, "SP": 76.0, "TMP": 16.784313725490197, "SLSW": 1}
```

**Comment by mak-gitdev** [comment, marked as answer]
Hi @HotteX,

If I understand correctly, you tried to add the support for A5-10-06, right ?
If so, could you please share your code ?
It will be easier to understand.

From your other message in #32, you wrote that your configuration for your A5-10-06 is:
```
[Temp/Eltako_1]
address         = 0xFFB17E00
rorg            = 0xA5
func            = 0x10
type            = 0x06
```
But from your log here, it seems that the address is 0xFFA0C800 / 0xFFA0C80. It this correct ?

**Reply by HotteX** [reply]
Hello mak,

yes, exactly. My code/config follows below. 
Yes I mixed up the Addresses. I have 4 of them, but they are configured all alike. 
To my understanding 0xFFA0C800 is the regular sensor while the 0x...01 address has information for the night mode (lowered set point)? I only used the regular address. I never used the night-mode switch.

The setpoint value is not a % (as the log sais). The value shown as % is the raw byte value (0-255)


/config/enoceanmqtt.devices
```
[Temp/FTR65HS]
address         = 0xFFA0C800
rorg            = 0xA5
func            = 0x10
type            = 0x06
```

/config/mapping.yaml
```
0xA5:
   0x10:
      0x06:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
         entities:
            - component: "sensor"
              name: "t_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
                 enabled_by_default: "true"
            - component: "sensor"
              name: "tempC"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
            - component: "sensor"
              name: "setpoint"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.SP | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "." #needs correction
# Switch: 2Do
```

**Reply by mak-gitdev** [reply]
Ok I see,

So what you can try is:
```yaml
0xA5:
   0x10:
      0x06:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
         entities:
            - component: "sensor"
              name: "t_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
                 enabled_by_default: "true"
            - component: "sensor"
              name: "tempC"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
            - component: "sensor"
              name: "setpoint"
              config:
                 state_topic: ""
                 value_template: "{{ (value_json.SP * 0.157) | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
```

**Reply by HotteX** [reply]
This works charmingly well. 
I also added the switch, now the Sensor works as expected. 

```
0x10:
      0x06:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
         entities:
            - component: "sensor"
              name: "t_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
                 enabled_by_default: "true"
            - component: "sensor"
              name: "tempC"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
            - component: "sensor"
              name: "setpoint"
              config:
                 state_topic: ""
                 value_template: "{{ (value_json.SP * 0.157) | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
            - component: binary_sensor
              name: "Nightmode"
              config:
                 state_topic: ""
                 value_template: >-
                    {% if value_json.SLSW == 1 %}OFF{% else %}ON{% endif %}

```

![Bildschirm­foto 2023-01-23 um 13 46 27](https://user-images.githubusercontent.com/67420589/214043393-6df4e66c-3d34-41cb-a86a-4a9f4474c90c.png)
