### DISCUSSION TITLE
now since the virtual buttons are select object nothing works

### DISCUSSION THREAD

**Discussion by commentsonly** [mak-gitdev/HA_enoceanmqtt#49] [Q&A]
I'm a bit stuck with some automations due to the change from buttons to selects.
In the past I used the buttons to being the trigger.
This worked in automations, scripts aswell as if being within a tap_action of buttoncards.

Now with the selects instead of buttons it remains to work in automations being an action but it fails if being used as a tap_action in buttoncards. Don't ask me where I'm wrong with my config.

this works in an automation:
```
    - service: select.select_option
      data:
        option: AE
      target:
        entity_id: select.e2m_virt_ar_esszimmer_action
```
and this fails in a custom:button-card
```
tap_action:
  action: call-service
  service: select.select_option
  service_data:
    option: AO
  target:
    entity_id: select.e2m_virt_ar_esszimmer_action

```
depending upon using data or service_data it throws differnt errors.
a missing entity_id, device_id if using ```service_data```
or with ```key not provided @data['option']```
```
tap_action:
  action: call-service
  service: select.select_option
  service_data:
    option: AO
  target:
    entity_id: select.e2m_virt_ar_esszimmer_action
```
Any example on how the new implementation should be used so it not only look cleaned from the number of entites span by the addon but also does work?

**Comment by mak-gitdev** [comment]
Hi @commentsonly,

Try:
```yaml
tap_action:
  action: call-service
  service: select.select_option
  service_data:
    option: AO
    entity_id: select.e2m_virt_ar_esszimmer_action
```

**Reply by commentsonly** [reply]
oh ... I tried like this: Continuing the discussion from [Strange (funny) problem with select. no matter if script or automation](https://community.home-assistant.io/t/strange-funny-problem-with-select-no-matter-if-script-or-automation/540009):

and yes ... looks as if I did a mistake in using device
```
  - device_id: 4edbb09d2d941d0aad37f6a59008e434
    domain: select
    entity_id: select.e2m_virt_ar_speisekammer_action
    type: select_option
    option: AO
```
against
'''
  - service: select.select_option
    data:
      option: AO
    target:
      entity_id: select.e2m_virt_ar_speisekammer_action
'''
dammit ......
but I'm still not satified with it ..... thinking about an easier way to get this solved.
```
virt_ar_speisekammer_ai:
  alias: virt_ar_speisekammer_ai
  sequence:
  - service: select.select_option
    data:
      option: AI
    target:
      entity_id: select.e2m_virt_ar_speisekammer_action
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: cover.ar_speisekammer
        state: opening
      - condition: state
        entity_id: cover.ar_speisekammer
        state: closing
    then:
    - service: cover.stop_cover
      data: {}
      target:
        entity_id: cover.ar_speisekammer
    else:
    - if:
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: cover.ar_speisekammer
          attribute: current_position
          above: 0
        - condition: state
          entity_id: cover.ar_speisekammer
          state: open
      then:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: cover.ar_speisekammer
      else:
      - service: script.dummy
        data: {}
  - service: select.select_option
    data:
      option: AI
    target:
      entity_id: select.e2m_virt_ar_speisekammer_action
  mode: single
  icon: mdi:transfer-down
```
curently stuck on using variables so that I won't need 2 of these (one for STOP/down the other for STOP/up) per shutter. But I'm not that deep into scripting or into passing variables.

thanks for the hint where I was wrong using the device service.

**Comment by commentsonly** [comment]
Hi Marc .... done. 😄 (no more mqtt buttons no templates and such like. I really love the addon in the new form. I saved me next to 80% of my previously required lines of YAML code to get the same thing done.

a unified script which I pass 3 informations from within the service_data section.
```
tap_action:
  action: call-service
  service: script.virt_ar_unified
  service_data:
    select: select.e2m_virt_ar_bad_action
    what: AO
    which: cover.ar_bad
```
no more code fiddling with the script, only 3 lines to change within the tap action.

script looks like this:
```
virt_ar_unified:
  alias: virt_ar_unified
  sequence:
  - service: select.select_option
    data:
      option: '{{ what }}'
    target:
      entity_id: '{{ select }}'
  - if:
    - condition: template
      value_template: '{{ is_state(which, "opening") or is_state(which, "closing")
        }}'
    then:
    - service: cover.stop_cover
      data: {}
      target:
        entity_id: '{{ which }}'
    else:
    - if:
      - condition: template
        value_template: '{{  (what == "AO") }}'
      then:
      - service: cover.open_cover
        data: {}
        target:
          entity_id: '{{ which }}'
      else:
      - service: cover.close_cover
        data: {}
        target:
          entity_id: '{{ which }}'
  - service: select.select_option
    data:
      option: None
    target:
      entity_id: '{{ select }}'
  mode: single
```
