### DISCUSSION TITLE
MICROPELT MVA003 EEP A5-20-01

### DISCUSSION THREAD

**Discussion by pphil78** [mak-gitdev/HA_enoceanmqtt#53] [Request]
Hello, reading all sensor is OK but I would like to send telegram to MVA like this one { "command": "direction":2,"delay":1,"SPS":1,"SP":19,"TMP":"139"} in order to program SP temp = 19°C. Can It be done with a virtual?

**Comment by mak-gitdev** [comment]
Hi @pphil78,

Virtual device would mean that HA will act like A5-20-01. This is certainly not what you want.

For the moment only direction 1 is supported.
You can test your command using for example an MQTT button in your configuration.yaml.

**Reply by pphil78** [reply]
Hi @mak-gitdev , thanks. For my try, could you tell me how can I set EEP to A5-20-01with MQTT button?

**Reply by mak-gitdev** [reply]
@pphil78,

In your Home Assistant configuration.yaml, simply add:
```yaml
mqtt:
  button:
    - name: "test_control_A52001"
      unique_id: uid_test_control_A52001
      command_topic: "<add your device root topic here>/req"
      payload_press: >-
        {"SPS":1,"SP":79,"TMP":139}
```
Notes:
- `TMP` seems to be a temperature from a room temperature sensor.
- I converted `SP` to its representation in the range 0...255 (SP*6.375).
- TMP range is 255...0 so to convert a temperature to this range you should do: 255-T*6.375
- You could find your device root topic as in the example below:
![image](https://user-images.githubusercontent.com/73297795/201531520-e0550a70-6dc2-4561-a338-4614208022f6.png)
![image](https://user-images.githubusercontent.com/73297795/201531644-230cbb1c-6d77-4f16-a1bc-6d02f1040b79.png)
- Do not forget to reload your manually configured MQTT entities
![image](https://user-images.githubusercontent.com/73297795/201531971-a280644c-8a4c-4ce3-8820-3c48b02cec6c.png)
