### DISCUSSION TITLE
Can you please add Eltako FTKE EEP F6-10-00 and FRW Smoke detector ? [DONE]

### DISCUSSION THREAD

**Discussion by Ekgev** [mak-gitdev/HA_enoceanmqtt#6] [Request] [answered]
I use a lot of enocean devices and would like to implement especially FTKE (F6-10-00) and FRW Smoke Detektor ? Would be very Great! Thanks!

**Comment by mak-gitdev** [comment]
Hi,

- F6-10-00 should be easy to add. If already done, how did you install HA_enoceanmqtt. Addon or standalone ?
- FRW seems to have EEP A5-30-03. Could you confirm ? Does it also have a temperature sensor ?

**Reply by Ekgev** [reply]
Hi, I use the Addon in Home Assistant. And yes, I guess EEP A5-30-03 could be right. It does not have a temp Sensor.

**Reply by stefanhofmann2** [reply]
I am using the Eltako window sensor FTKE EEP F6-10-00 too. Where can i find the mapping file? Thanks

**Reply by mak-gitdev** [reply]
Hi @stefanhofmann2,

Could you please open a new discussion. It will be easier to track in the case someone else has the same question :+1:

**Comment by mak-gitdev** [comment, marked as answer]
Ok.

I have an initial support available for your F6-10-00.

As I don't have access to all EnOcean devices, I organized this script so that the end-user can do field tests when requesting a new device support.
For that, it requires that you modify your mapping.yaml file.

Here are the steps to follow:
- First please stop the addon.
- Then copy the [mapping.yaml file](https://github.com/mak-gitdev/HA_enoceanmqtt/blob/support-f6-10-00/mapping.yaml) to your home assistant `/config/mapping.yaml`. Note that `/config/` is the directory where you have your Home Assistant `configuration.yaml` file.
- Then, as you are using the addon, you have a configuration entry named `mapping_file`. Set this entry to `/config/mapping.yaml` and save your configuration.
- Finally, add your F6-10-00 device in your device file then restart the addon.

After that you should see entities corresponding to your device in HA.
Please then report whether the created entities are OK or require modifications, with a picture if possible.

**Reply by Ekgev** [reply]
Thanks, works well, state3 is used for open closed indication.

**Reply by mak-gitdev** [reply]
Great it works !
State2 is for open/close windows.
State3 is for tilt and turn windows (open/close/tilt).

**Reply by commentsonly** [reply]
What I do wonder .... if you use the Eltako FTKE-rw which only offers 2 states (open/closed) State2 is non-functional at my end.
It does make use of the State3 which is a pitty since that's a sensor not a binary sensor with all it's miseries.
A binary_sensor would allow to define the device_class door or window acting as On/Off on the commandline which auto turns into Open/Closed by HA itself. No need to fiddle with texts inside the mapping.yaml.
Not to mention it'll get the device_class icons automatically.
Can't be that hard to make it use the binary sensor .... but I had no time yet.

But there must be a way to divert depending upon the manufacturer if I understand it right whart the iobrioker implementation does. I think they check for some bytes diverting upon if it's a manufacturer which does use an ordinary window-handle (3 states) against a simple switch only offering 2 states. But I'm unsure if the embyt python allows for that.
But I'd still recommend to not use string terms in the mapping.yaml if possible for the simple reason that HA would take the defined language into account on converting on/off into open/closed using the device_class. AFAIK.

**Reply by mak-gitdev** [reply]
Could you please replace the code F6-10-00 in mapping.yaml by this one and report whether state2 is working now ?
```yaml
   0x10:
      0x00:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
         entities:
            - component: binary_sensor
              name: "state_2p"
              config:
                 state_topic: ""
                 value_template: >-
                   {% if value_json.WIN == 3 %}OFF{% else %}ON{% endif %}
            - component: sensor
              name: "state_3p"
              config:
                 state_topic: ""
                 value_template: >-
                   {% if value_json.WIN == 3 %}OFF{% elif value_json.WIN == 1 %}tilt{% else %}ON{% endif %}
```

**Reply by Ekgev** [reply]
Hi, State2 is still "unknown", but State3 shows the correct value / status

**Reply by Ekgev** [reply]
For clarification: State3 shows open/closed.

**Reply by mak-gitdev** [reply]
Could you share a screenshot ?
Strange because it works fine on my side.

**Reply by Ekgev** [reply]
![grafik](https://user-images.githubusercontent.com/118467264/203821126-ecca225c-2058-4d14-a08b-0a6ee2bfc9f7.png)

**Reply by Ekgev** [reply]
![grafik](https://user-images.githubusercontent.com/118467264/203821559-7ecfdb48-d736-48fa-9be3-60cce3e25de9.png)

**Reply by Ekgev** [reply]
Before I restartet HA, now I restarted the Addon. Now it is different: 
![grafik](https://user-images.githubusercontent.com/118467264/203822441-3d7a050b-c9c4-4c1e-ab6f-7f295311c3b8.png)
![grafik](https://user-images.githubusercontent.com/118467264/203822822-4a65a840-829f-4dd2-bcd7-ceccb3d573df.png)

**Reply by Ekgev** [reply]
The Status is in State2 as well State3 correct

**Reply by mak-gitdev** [reply]
Yes, you have to restart the addon to take into account changes made in mapping.yaml

**Reply by Ekgev** [reply]
Sorry, I thought that a restart of HA would be sufficient. Seems not. Anyway, sorry for that!

**Reply by mak-gitdev** [reply]
No problem at all.
But you're right, that's strange. I would have thought that a restart of HA would be sufficient.

Oh wait ! I may just get it I think.
It is all about containers, the addon as well as HA. Restarting HA only restart the HA (core?) container but not the other containers (a.k.a the addons). That may be that.

**Reply by commentsonly** [reply]
Yep now both  do work .... but you still missed the vital line, the "device_class"

```
            - component: binary_sensor
              name: "state_2p"
              config:
                 device_class: window
                 state_topic: ""
                 value_template: >-
                   {% if value_json.WIN == 3 %}OFF{% else %}ON{% endif %}
```
![snappy](https://user-images.githubusercontent.com/35866491/203830739-bcc13091-c50e-410e-9777-ce24f09e2755.png)
