### DISCUSSION TITLE
EEP A5-38-08 for Eltako FD62NPN-230

### DISCUSSION THREAD

**Discussion by hoeffyF** [mak-gitdev/HA_enoceanmqtt#71] [Request]
Dear mak-gitdev,

I am new at HA with HA_enoceanmqtt and it works fine with nodon RS.
But I have 2 Eltako FD62NPN-230 with EEP A5-38-08.
Could you help me to implement it?

Best regards
hoeffy

**Comment by mak-gitdev** [comment]
Hi @hoeffyF,

Sorry for the late reply.
Which kind of installation are you using ? Addon, docker, standalone ?
As well, what is your HA installation ? HAOS, Supervised, Container, Core ?

Thanks

**Reply by hoeffyF** [reply]
Dear @mak-gitdev,

Sorry for late answer, too. ;-)
I am using HAOS with Addon.

I think I have got problems to use the "learn" button, too.
Logs:
`INFO: learn request not emitted to mqtt`

Best regards
hoeffy

**Reply by mak-gitdev** [reply]
Hi @hoeffyF,

Thanks for the reply. Let me see how I can add support for this one.

Regarding the message you referred to, it is not a problem, just an information that learn telegram contents are not forwarded to the MQTT broker, which is the expected behavior.
In fact, all the learn logic is handled by the Python EnOcean library. The switch I made available in HA is just used to enable/disable that logic.

**Reply by hoeffyF** [reply]
Thank you.
Looking forward to it.

**Reply by mak-gitdev** [reply]
Hi @hoeffyF,

I think you can use a [custom mapping file](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Examples#using-custom-mappingyaml-andor-eepxml-files) and add this new entry to EEP A5-38-08:
```yaml
            - component: "light"
              name: "light_COM2"
              config:
                 schema: "template"
                 command_topic: "req"
                 command_on_template: >-
                   {"COM":"2","EDIM":"100","RMP":"1","EDIMR":"0","STR":"0","SW":"1","send":"clear"}
                 command_off_template: >-
                   {"COM":"2","EDIM":"0","RMP":"1","EDIMR":"0","STR":"0","SW":"0","send":"clear"}
```

Then create a new device with EEP A5-38-08 and the address of your module in your device file.

Note that for this to work, you will have to teach your USB300 to your FD62NPN but I am not sure how this should be done.
