### DISCUSSION TITLE
Add support for D2-01-01

### DISCUSSION THREAD

**Discussion by albenoit** [mak-gitdev/HA_enoceanmqtt#75] [Request]
Wow, what a fantastic library, thanks!

May i suggest to integrate  the D2-01-01 profile ? This is actually useful for telerrupters/(WIRED INPUT DIN RAIL RECEIVER WITH TOGGLE SWITCH) often installed in corridors and so on. This model corresponds: https://www.trio2sys.fr/index.php/fr/produits-enocean-sans-fil-sans-pile-interoperable/recepteur-sans-fils-sans-pile-interoperable-enocean/42

Thanks !

**Comment by mak-gitdev** [comment]
Hi @albenoit,

It will be added in the next release.
While waiting for that one, you can use a [custom mapping file](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Examples#using-custom-mappingyaml-andor-eepxml-files) and add the following under 0xD2-0x01:
```yaml
      0x01:
         device_config:
            command: "CMD"
            channel: "CMD"
            log_learn: ""
            direction: ""
            answer: ""
         entities:
            - component: "switch"
              name: "switch"
              config:
                 state_topic: "CMD4"
                 state_on: "100"
                 state_off: "0"
                 value_template: "{{ value_json.OV }}"
                 command_topic: "req"
                 payload_on: >
                   {"CMD":"1","DV":"0","IO":"0","OV":"100","send":"clear"}
                 payload_off: >
                   {"CMD":"1","DV":"0","IO":"0","OV":"0","send":"clear"}
                 device_class: outlet
            - component: "button"
              name: "query_status"
              config:
                 command_topic: "req"
                 payload_press: >-
                   {"CMD":"3","IO":"30","send":"clear"}
            - component: binary_sensor
              name: "LC"
              config:
                 state_topic: "CMD4"
                 payload_on: "on"
                 payload_off: "off"
                 value_template: >-
                    {% if value_json.LC == 1 %}on{% else %}off{% endif %}
```
