### DISCUSSION TITLE
Support for EEP A5-09-04 - Eltako FCO2TS

### DISCUSSION THREAD

**Discussion by tomknocke** [mak-gitdev/HA_enoceanmqtt#84] [Request]
Hi,

i would like to ask for support to configure the Eltako FCO2TS.

Seems EEP A5-09-04 is not supported, yet.

Thanks.

Tom

**Comment by mak-gitdev** [comment]
Hi @tomknocke,

Please use a [custom mapping file](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Examples#using-custom-mappingyaml-andor-eepxml-files) and add the following code in the 0xA5 section:
```yaml
   0x09:
      0x04:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
            direction: ""
            answer: ""
         entities:
            - component: "sensor"
              name: "humidity"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.HUM }}"
                 device_class: "humidity"
                 unit_of_measurement: "%"
            - component: "sensor"
              name: "concentration"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.Conc }}"
                 device_class: "carbon_dioxide"
                 unit_of_measurement: "ppm"
            - component: "sensor"
              name: "temperature"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
```

Please report if everything is OK.

**Comment by mak-gitdev** [comment]
[Status](https://github.com/users/mak-gitdev/projects/1/views/1?pane=issue&itemId=35608105)

**Reply by tomknocke** [reply]
Hi,

thanks for the quick reply.

Yesterday evening i tried it on my own ,and it works.
I found the debug mode very helpfull, because i recognized the sensor values already found, and only mapping to HA MQTT was missing.
So i copied a part of other sensor and added CO2.
You code seems to be more clean and better. Thanks

Below is the code which works for 100% sure:
```yaml
   0x09:
      0x04:
         device_config:
            command: ""
            channel: ""
            log_learn: ""
            direction: ""
            answer: ""
         entities:
            - component: "sensor"
              name: "h_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.HUM }}"
                 device_class: "humidity"
                 unit_of_measurement: "%"
            - component: "sensor"
              name: "Conc_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.Conc }}"
                 device_class: "carbon_dioxide"
                 unit_of_measurement: "ppm"
            - component: "sensor"
              name: "t_raw"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
                 enabled_by_default: "false"
            - component: "sensor"
              name: "tempC"
              config:
                 state_topic: ""
                 value_template: "{{ value_json.TMP | round(1) }}"
                 device_class: "temperature"
                 unit_of_measurement: "°C"
```
