### DISCUSSION TITLE
Unable to set cover

### DISCUSSION THREAD

**Discussion by didi31** [mak-gitdev/HA_enoceanmqtt#93] [Q&A] [answered]
I would like to move from Domoticz to Home assistant.
I have 3 covers module EVOLOGY (Leroy merlin) which are provided by Nodon and Nodon told me that they are exactly the same than the Nodon ones.
I got the identity of each module from the enocean hardware of Domoticz.
Contact switch are working perfectly.
I did the following for the cover.
  - Set the conf:
      [Volet/chambre]
      address         = 0x05A21EE5
      rorg            = 0xD2
      func            = 0x05
      type            = 0x00
- Switch the learn button to On
- Follow the procedure for pairing.

The module does not react as written In the EVOLOGY procedure but I can move the cover up with HA.
However as soon as the cover is open, the arrow to move the cover down is greyed and I cannot close it.
Is there something wrong in what I did?

**Comment by mak-gitdev** [comment]
Hi @didi31,

What happens if you press the cover up button ?
UP and DOWN commands may be inverted.

**Comment by didi31** [comment]
For a position in-between (where both arrows are active) it works as expected. Left arrow move the cover UP and right arrow move the cover down.
But when the cover is fully open or closed, the greyed arrow is not the correct one.
When cover is closed I cannot open it and when it is open, I cannot close it.

13 nov. 2023 12:19:15 mak-gitdev ***@***.***>:

**Comment by didi31** [comment]
Something strange on the cover properties.

[cid:eu.faircode.email.544]
![Screenshot_2023-11-13-15-29-51-177_com android chrome](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/46863073/879ac76c-ce03-4757-bab5-9c142891b295)
Cover is open in the Real life lol
When I installed the add-on, I had 2 choices, Deprecated and dev I selected the dev version.

**Comment by mak-gitdev** [comment]
Hi @didi31,

Ok I see.
Please use a [custom mapping file](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Using-custom-mapping.yaml-and-or-EEP.xml-file%28s%29) and replace the current D2-05-00 mapping by this one:

```yaml
   0x05:
      0x00:
         device_config:
            command: "CMD"
            channel: "CMD"
            log_learn: ""
            direction: ""
            answer: ""
         entities:
            - component: "cover"
              name: "cover"
              config:
                 command_topic: "req"
                 payload_open: >-
                    {"CMD":"1","POS":"0","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_close: >-
                    {"CMD":"1","POS":"100","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_stop: >-
                    {"CMD":"2","CHN":"0","send":"clear"}
                 position_topic: "CMD4"
                 position_template: "{{ value_json.POS }}"
                 set_position_topic: "req"
                 set_position_template: >-
                    {"CMD":"1","POS":"{{ position }}","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 tilt_status_topic: "CMD4"
                 tilt_status_template: "{{ value_json.ANG }}"
                 tilt_command_topic: "req"
                 tilt_command_template: >-
                    {"CMD":"1","POS":"127","ANG":"{{ tilt_position }}","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
            - component: "cover"
              name: "cover2"
              config:
                 command_topic: "req"
                 payload_open: >-
                    {"CMD":"1","POS":"0","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_close: >-
                    {"CMD":"1","POS":"100","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_stop: >-
                    {"CMD":"2","CHN":"0","send":"clear"}
                 position_topic: "CMD4"
                 position_open: "0"
                 position_closed: "100"
                 position_template: "{{ value_json.POS }}"
                 set_position_topic: "req"
                 set_position_template: >-
                    {"CMD":"1","POS":"{{ position }}","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 tilt_status_topic: "CMD4"
                 tilt_status_template: "{{ value_json.ANG }}"
                 tilt_command_topic: "req"
                 tilt_command_template: >-
                    {"CMD":"1","POS":"127","ANG":"{{ tilt_position }}","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
```

Then use the cover2 entity and report the behavior please.

**Reply by didi31** [reply]
Hi
I found the way to create the mapping file but how to use the cover2 settings?

**Reply by mak-gitdev** [reply]
@didi31,

Simply restart the addon.
You will then have a second cover entity named e2m_xxx.cover2

**Comment by didi31** [comment]
I have nothing more. 😔
I attached the log and the mapping file

14 nov. 2023 11:44:11 mak-gitdev ***@***.***>:

**Reply by didi31** [reply]
This template works
```python
     vr_salon:
        unique_id: ca169872-a37a-4f51-a767-175facf6cc4
        friendly_name: "Volet du salon"
        device_class: "blind"
        position_template: "{{ 100 - state_attr('cover.e2m_Volet_salon_cover','current_position')|int }}"
        open_cover:
          - service: cover.open_cover
           target:
              entity_id: cover.e2m_Volet_salon_cover
        close_cover:
          - service: cover.close_cover
           target:
              entity_id: cover.e2m_Volet_salon_cover
        stop_cover:
          - service: cover.stop_cover
          target:
              entity_id: cover.e2m_Volet_salon_cover
        set_cover_position:
          - service: cover.set_cover_position
          data:
              position: "{{100 - position }}"
          target:
              entity_id: cover.e2m_Volet_salon_cover
```

**Reply by mak-gitdev** [reply]
@didi31,

> I attached the log and the mapping file
There are no file attached. Could you resend them please ?

**Reply by didi31** [reply]
[log.docx](https://github.com/mak-gitdev/HA_enoceanmqtt/files/13349110/log.docx)
[mapping.txt](https://github.com/mak-gitdev/HA_enoceanmqtt/files/13349128/mapping.txt)

**Reply by didi31** [reply]
I see them inside MQTT explorer but not in the MQTT integration
However, it seems that the position is not correct. When the cover is fully opened, it should be 100 whilst it return 0.
If I set the position to 90% it close the cover to 10%.

**Reply by mak-gitdev** [reply]
@didi31,

If you look at the mapping for cover2 entity, you will see that I indicate open as 0 and close as 100 as this is what is reported by the EEP.
That's why I would like you to test that cover2 entity.
Could you please regenerate the log with debug activated ?
Also could you please share a screenshot of the device page in the MQTT integration ?

Thanks.

**Reply by didi31** [reply]
Inside HA the rule seems to be  inverted. 
If I look at the cover template:
```
position_template [template](https://www.home-assistant.io/docs/configuration/templating/) (Optional)

Defines a template to get the position of the cover. Legal values are numbers between 0 (closed) and 100 (open). If the template produces a None value the current position will be set to unknown.
``` 
[enoceanmqtt.log](https://github.com/mak-gitdev/HA_enoceanmqtt/files/13349493/enoceanmqtt.log)
![MQTT_2](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/46863073/42c60967-16e1-4bb7-93f1-b63582e2c085)
![MQTT_1](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/46863073/0ed4b992-f08f-4b55-b234-1557f4f4f242)

**Comment by mak-gitdev** [comment]
@didi31,

I made a mistake in the mapping for cover2. Please change the lines:
```yaml
                 position_open: "0"
                 position_closed: "100"
```
by:
```yaml
                 position_open: 0
                 position_closed: 100
```

The cover2 entity should appear now.

<br></br>
> Inside HA the rule seems to be inverted.
If I look at the cover template:

Yes, I know and that's why for cover2 entity, I added that `position_open` is 0 and `position_closed` is 100 so that HA knows that when the EEP sends 0 for position, it means open and 100 means closed.
You can have a look at [cover.mqtt](https://www.home-assistant.io/integrations/cover.mqtt/) for more details.
I know we can do what you did in your template but I just want to check that this can work as well :wink:.

**Reply by didi31** [reply, marked as answer]
I removed:
  -  position_open
  -  position_closed
  -  tilt_status_topic
  -  tilt_status_template
  -  tilt_command_topic
  -  tilt_command_template

changed:
  -  position_template to "{{ 100 - value_json.POS }}"
  - set_position_template to  {"CMD":"1","POS":"{{ 100 - position }}","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
  
and it work fine.

```
            - component: "cover"
              name: "cover2"
              config:
                 command_topic: "req"
                 payload_open: >-
                    {"CMD":"1","POS":"0","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_close: >-
                    {"CMD":"1","POS":"100","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
                 payload_stop: >-
                    {"CMD":"2","CHN":"0","send":"clear"}
                 position_topic: "CMD4"
                 position_template: "{{ 100 - value_json.POS }}"
                 set_position_topic: "req"
                 set_position_template: >-
                    {"CMD":"1","POS":"{{ 100 - position }}","ANG":"127","REPO":"0","LOCK":"0","CHN":"0","send":"clear"}
``` 
Thanks a lot for your support and the big work you did on this module.
