### DISCUSSION TITLE
Add full support for A5-06-01 Eltako light sensor

### DISCUSSION THREAD

**Discussion by olivierkeke** [mak-gitdev/HA_enoceanmqtt#95] [Request] [answered]
Hi,
Thanks for this nice work! I'm currently trying to get rid of my openhab server I'm keeping only as an enocean to mqtt gateway.

I have a light sensor from Eltako with EEP A5-06-01.
With profile A5-06-01 in HA_enoceanmqtt illuminance values are stuck above 300 lx.
I have not this problem with the openhab enocean addon (range 0lx to 30000lx) since it makes a specific case for Eltako light sensors : https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_06 

Is a specific case for Eltako light sensor feasible in HA_enoceanmqtt?

**Comment by mak-gitdev** [comment]
Hi @olivierkeke, 

Is it the FHD60SB ?

**Reply by olivierkeke** [reply]
Yes! I found [this specifcation](https://www.eltako.com/fileadmin/downloads/fr/_bedienung/FHD60SB_30000462-1_fr.pdf) which seems clear concerning databytes description.

**Reply by mak-gitdev** [reply, marked as answer]
@olivierkeke,

Eltako devices are planned to be handled specifically as some of them use customized EEPs.
But as a temporary solution, you can use a [custom mapping file](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Using-custom-mapping.yaml-and-or-EEP.xml-file%28s%29) and add the following entity code in the A5-06-01 section:
```yaml
            - component: "sensor"
              name: "fhd60sb"
              config:
                 state_topic: ""
                 value_template: >-
                   {% if (value_json.ILL2|int) == 300 %}
                     {{ (value_json.SVC * 50) | round(1) }}
                   {% else %}
                     {{ value_json.ILL2 | round(1) }}
                   {% endif %}
                 device_class: "illuminance"
                 unit_of_measurement: "lx"
```
Not sure it is OK so please try it and report the outcome.
